name: UnicornHK
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2759857
title: HKUnicornHK
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0278dc'
    - '#5f729a'
    - '#000500'
    - '#2baacd'
  brandStrength: 0.4910394
  lightness: 0.75
  saturation: 0.8351254
  rhythmicContrast: 0.8870968
purpose: []
