name: UnicornHK
favicon: null
layout_spectrum: 0.6702509
typography_spectrum: 0.3960573
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#FD4746'
    - '#000000'
    - '#DAAC3D'
    - '#55D037'
  brandStrength: 0.875
  lightness: 0.874552
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
